### ISSUE TITLE
To-do:

### ISSUE THREAD

**Issue by fintzij** [fintzij/stemr#3]
Running list of various things I need to update in this package:
- [x] Resolve crashing due to bug in XPtr destruction. 
- [x] Ryacas compatibility
- [x] Get rid of t0 inference.
- [x] Block sampling for parameters with MH + adaptive MCMC infrastructure. Should be similar to MVNSS. 
- [x] Allow for different samplers for different blocks of parameters. 
- [x] Unified wrapper for LNA and ODE inference.
- [x] Minweke tests for samplers.
- [x] Beta-binomial emission distribution.
- [x] Remove beta-binomial and link against extraDistr headers if that package ever exports functions to make them C++ callable.
- [ ] compile dynamics and measurement process together in make_stem instead of in stem_dynamics and stem_measurement separately.
- [ ] fit_stem should return the log-posterior so the user doesn't always have to sum it's constituent parts.
- [ ] Flag for parameters that are declared but never used.
- [ ] Only allow a stem object to have one method compiled at a time for safety.
- [ ] Option to sample marginal posterior LNA paths by sampling additional standard normal random variates not conditioned on data but conditional on posterior draws of model parameters.
- [ ] Retool and streamline simulation/prediction.
- [ ] New vignettes.
- [ ] Utility functions for posterior processing.
- [ ] Push to CRAN? Is this worth the headache?
- [ ] Refactor handling of strata so they are conditionally independent (MAJOR update).
- [ ] Functionality for within-chain parallelization to solve ODEs for conditionally independent strata (MAJOR update).
- [ ] Tidy MCMC objects?
- [ ] Improve parsing functions
- [ ] Transfer errors and warnings to self contained functions for checking validity of model specification.
- [ ] Verify that measurement processes related to prevalence are handled correctly in inference.
- [ ] Allow for LNA not to necessarily restart at every time point.
- [ ] Return only lower triangular part of LNA covariance when solving ODEs. No need to return the entire matrix.
- [ ] Custom measurement processes to allow for second stage model as well as reporting delays in the future. 
- [ ] With previous task, function to give sample objects to help user define likelihood.
- [ ] Option to return centered LNA moments when simulating/doing inference. Option not to return non-centered LNA draws.
- [ ] Solve ODEs using [Julia solvers](https://github.com/SciML/diffeqr) or with Stan instead of Boost? Is this possible?
- [ ] testing with [testthat](https://testthat.r-lib.org)
- [ ] report coverage with [covr](https://covr.r-lib.org)
- [ ] allow for time varying parameters that are a function of time varying covariates and time homogeneous parameters

**Comment by damonbayer** [comment]
Re:  Solve ODEs using Julia solvers or with Stan instead of Boost? Is this possible?

https://github.com/SciML/diffeqr

**Comment by kevinkiernan** [comment]
New vignettes would be greatly appreciated! I had the previous version of stemr working well for generating SEMs for the COVID outbreak based on death incidence, but the update to Ryacas broke my workflow.

If new vignettes are not imminent, perhaps I could get the answers to a couple of questions?
1. For the priors input to the function parblocks, is logprior the same function as what you were calling prior_density in previous versions? If not, how is logprior specified?
2. Is the intializer input to parblocks used to initialize the parameters in the same manner as the function assigned to stemobj$dynamics$parameters in previous versions? (i.e. to add a random perturbation to the starting parameter value)

These were my assumptions after reading the commented code, but I get an initialization error when fit_stem tries to call initialize_lna.

**Comment by fintzij** [comment]
Moved questions from @kevinkiernan to a [separate thread](https://github.com/fintzij/stemr/issues/9#issue-701110709).
